### ISSUE TITLE
Python based error occurring while processing requests on RP_IVR analytics

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/RP_IVR_analytics#484]
**Describe the bug**
We are getting some Python-level error logs on the logging and monitoring dashboard for the RP_IVR cloud function.

**Add diagnosis details**
- The error was regarding the `google-cloud-logging` package used to generate custom logs in the application. We are using this package currently in our application to create different levels of logs like:
  - DEBUG
  - INFO
  - ERROR
  - WARNING
- The package was throwing some errors because of the dependency issue with the Python flask.

**Issue logs:**

Error 1:
```
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/functions_framework/__init__.py", line 361, in create_app
    spec.loader.exec_module(source_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/main.py", line 2, in <module>
    from api import app, helpers, services, models
  File "/workspace/api/helpers/__init__.py", line 2, in <module>
    from .db_helper import *
  File "/workspace/api/helpers/db_helper.py", line 3, in <module>
    from utils.loggingutils import logger
  File "/workspace/utils/__init__.py", line 1, in <module>
    from .loggingutils import *
  File "/workspace/utils/loggingutils.py", line 13, in <module>
    log_client = gcloud_logging.Client() 
```

Error 2:
```
 File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)"
```

**Expected behavior**
- [x] Find out the cause of the issue.
- [x] Figure out the action items to fix the issue.

**Screenshots**
<img width="2473" alt="Screenshot 2024-06-12 at 7 23 18 PM" src="https://github.com/DostEducation/RP_IVR_analytics/assets/96137915/7d853a47-b64a-409d-ac4d-8c56e2e4e8d7">

**Impact**
Error logs count: 30

**Criticality**
Medium

**Acceptance Criteria**
- [x] The Python and the dependencies should work fine.

**Documentation**
Add whatever documentation will be required here.

**Comment by Sachinbisht27** [comment]
### Diagnosis Details

**Description:** 
- We are currently using the `google-cloud-logging` package version 3.5.0 and the latest version of the package is 3.10.0.
- The package was throwing an error because of the dependency issue with the Python flask.

**To reproduce:**
Try to replicate the production environment locally and generate Application-level logs.

**Root cause**
_The `google-cloud-logging` package had dependency issues with the Python flask._

**Action items**
- [ ] Upgrade the `google-cloud-logging` and its dependencies to the latest supported version of the Python flask.

**Steps to fix:**
- [ ] Figure out the latest supported version of the `google-cloud-logging` package.
- [ ] Update the package and dependencies.
- [ ] Test by generating different levels of logs so frequently.
- [ ] Deploy on Staging and test there as well.
- [ ] Deploy the changes on the Production environment.

**Comment by Sachinbisht27** [comment]
Closing this Item as the Diagnosis is completed and the Action items to fix the issue are figured out. We will be targeting the action item in a separate issue. #485

**Comment by Sachinbisht27** [comment]
**This issue again started occurring on 12 Dec 2024:**

**Error log:**
```
{
  "textPayload": "Traceback (most recent call last):\n  File \"/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py\", line 1478, in __call__\n    return self.wsgi_app(environ, start_response)",
  "insertId": "675c5614000222de2da2f256",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "region": "asia-south1",
      "project_id": "cryptic-gate-211900",
      "function_name": "rp-ivr-analytics-prod"
    }
  },
  "timestamp": "2024-12-13T15:43:16.139998Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "cxnc9gn33qb9",
    "instance_id": "0066d924808c212f914ae8a2baafa371f9865390e11e2ca4b54da6fae3468624edbe3fe6f686f7eb33ff193cde558fd9b6fd7cc2c344e8c9ca438e54175247ea8bd3ec8fcd0d86b304f325147652f9bef487034f9d",
    "runtime_version": "python311_20241208_3_11_10_RC00"
  },
  "logName": "projects/cryptic-gate-211900/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/cryptic-gate-211900/traces/b25ee0f681d5047f35e6ee087780d02a",
  "receiveTimestamp": "2024-12-13T15:43:16.242092738Z",
  "errorGroups": [
    {
      "id": "CIasqKfEo-iDogE"
    }
  ]
}
```

**Screenshot:**
<img width="1403" alt="image" src="https://github.com/user-attachments/assets/0d3e912e-c632-42c9-85f3-3285fd1b7f6b" />
